version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: tcc
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=tcc

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:8080"
    depends_on:
      - backend

volumes:
  db_data:
